//
//  DesignMarkdownFixtures.swift
//  EaselDesignSystemsTests
//

import Foundation

/// Fixtures are built from line arrays so YAML indentation is unambiguous
/// (independent of Swift multiline-literal de-indentation).
enum DesignMarkdownFixtures {
  /// A canonical, spec-clean sample.
  static let heritage = [
    "---",
    "version: alpha",
    "name: Heritage",
    "description: A premium editorial system.",
    "colors:",
    "  primary: \"#1A1C1E\"",
    "  secondary: \"#6C7278\"",
    "  tertiary: \"#B8422E\"",
    "  neutral: \"#F7F5F2\"",
    "typography:",
    "  display-lg:",
    "    fontFamily: Public Sans",
    "    fontSize: 3rem",
    "    fontWeight: 700",
    "  body-md:",
    "    fontFamily: Public Sans",
    "    fontSize: 1rem",
    "  label-caps:",
    "    fontFamily: Space Grotesk",
    "    fontSize: 0.75rem",
    "rounded:",
    "  sm: 4px",
    "  md: 8px",
    "spacing:",
    "  sm: 8px",
    "  md: 16px",
    "components:",
    "  button-primary:",
    "    backgroundColor: \"{colors.tertiary}\"",
    "    textColor: \"{colors.neutral}\"",
    "    rounded: \"{rounded.sm}\"",
    "    padding: 12px",
    "  button-primary-hover:",
    "    backgroundColor: \"{colors.secondary}\"",
    "---",
    "",
    "## Overview",
    "",
    "Architectural Minimalism meets Journalistic Gravitas.",
    "",
    "## Colors",
    "",
    "The palette is rooted in high-contrast neutrals.",
    "",
    "## Typography",
    "",
    "Public Sans carries the structural type.",
  ].joined(separator: "\n")

  /// An imperfect, third-party-style sample: aliased + out-of-order sections,
  /// no primary color, a low-contrast component, a broken ref, and an unknown key.
  static let imperfect = [
    "---",
    "name: Imperfect",
    "brandTone: playful", // unknown key
    "colors:",
    "  brand: \"#FFFFFF\"",
    "  ink: \"#AAAAAA\"",
    "components:",
    "  card:",
    "    backgroundColor: \"{colors.brand}\"",
    "    textColor: \"{colors.ink}\"", // ~2.3:1 contrast → fails AA
    "  banner:",
    "    backgroundColor: \"{colors.missing}\"", // broken ref
    "---",
    "",
    "## Colors",
    "",
    "Loud and friendly.",
    "",
    "## Overview", // out of order (Overview after Colors)
    "",
    "A playful identity.",
  ].joined(separator: "\n")

  /// A prose-only, third-party writeup with no YAML front matter. This mirrors
  /// the numbered-section style common in generated design-system reports.
  static let lovableProse = [
    "# Design System Inspired by Lovable",
    "",
    "## 1. Visual Theme & Atmosphere",
    "",
    "Lovable's website radiates warmth through restraint.",
    "",
    "## 2. Color Palette & Roles",
    "",
    "### Primary",
    "- **Cream** (`#f7f4ed`): Page background, card surfaces, button surfaces.",
    "- **Charcoal** (`#1c1c1c`): Primary text, headings, dark button backgrounds.",
    "- **Off-White** (`#fcfbf8`): Button text on dark backgrounds.",
    "",
    "### Neutral Scale (Opacity-Based)",
    "- **Muted Gray** (`#5f5f5d`): Secondary text, descriptions, captions.",
    "- **Charcoal 40%** (`rgba(28,28,28,0.4)`): Interactive borders, button outlines.",
    "",
    "### Surface & Border",
    "- **Light Cream** (`#eceae4`): Card borders and dividers.",
    "",
    "## 3. Typography Rules",
    "",
    "### Font Family",
    "- **Primary**: `Camera Plain Variable`, with fallbacks: `ui-sans-serif, system-ui`",
    "",
    "### Hierarchy",
    "| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |",
    "|------|------|------|--------|-------------|----------------|-------|",
    "| Display Hero | Camera Plain Variable | 60px (3.75rem) | 600 | 1.00-1.10 (tight) | -1.5px | Maximum impact |",
    "| Section Heading | Camera Plain Variable | 48px (3.00rem) | 600 | 1.00 (tight) | -1.2px | Feature section titles |",
    "| Body | Camera Plain Variable | 16px (1.00rem) | 400 | 1.50 | normal | Standard reading text |",
    "",
    "## 4. Component Stylings",
    "",
    "### Buttons",
    "",
    "**Primary Dark (Inset Shadow)**",
    "- Background: `#1c1c1c`",
    "- Text: `#fcfbf8`",
    "- Padding: 8px 16px",
    "- Radius: 6px",
    "- Use: Primary CTA",
    "",
    "**Ghost / Outline**",
    "- Background: transparent",
    "- Text: `#1c1c1c`",
    "- Padding: 8px 16px",
    "- Radius: 6px",
    "- Border: `1px solid rgba(28,28,28,0.4)`",
    "",
    "### Cards & Containers",
    "- Background: `#f7f4ed`",
    "- Border: `1px solid #eceae4`",
    "- Radius: 12px",
    "",
    "## 5. Layout Principles",
    "",
    "### Spacing System",
    "- Base unit: 8px",
    "- Scale: 8px, 10px, 12px, 16px, 24px, 32px, 40px, 56px",
    "",
    "### Border Radius Scale",
    "- Micro (4px): Small buttons, interactive elements",
    "- Standard (6px): Buttons, inputs, navigation menu",
    "- Comfortable (8px): Compact cards",
    "- Card (12px): Standard cards, image containers",
    "- Full Pill (9999px): Action pills and icon buttons",
    "",
    "## 6. Depth & Elevation",
    "",
    "Lovable's depth system is intentionally shallow.",
    "",
    "## 7. Do's and Don'ts",
    "",
    "- **Do** use the warm cream background.",
    "- **Don't** use pure white as a page background.",
  ].joined(separator: "\n")
}
